### ISSUE TITLE
I wonder if there is a way to 'hook' the Clipboard so if new text is placed there it automatically gets added to your 'database'???

### ISSUE THREAD

**Issue by WWPowell-ga** [hartkemd/TextCopier#1]

**Comment by WWPowell-ga** [comment]
I wonder if there is a way to 'hook' the clipboard so that every time text is added it gets automagically added to your 'database'

**Comment by hartkemd** [comment]
Hello. Thanks for your idea. I had thought of something similar to that, where the app would essentially save everything - or some things - you copied to the clipboard, but then some concerns started creeping in, such as how I would handle sensitive data. I'm not yet ready to deal with the privacy and security concerns that would open up, so I'm keeping that feature out for now.
