### ISSUE TITLE
Some problems after last commit

### ISSUE THREAD

**Issue by MadalinCernat** [hartkemd/TextCopier#3]
I've seen some problems in the application after you started the work on the Sqlite data access.

1. The IDataAccess interface is meant to be implemented by the SqliteCrud class. The SqliteDataAccess is just a helper for SqliteCrud that should be used just in the class library.

2. If you try to implement IDataAccess for SqliteCrud, you will notice there are some problems. 
    - Sqlite methods shouldn't require a filePath
    - The WriteAllRecords doesn't apply to Sqlite because only text files rewrite all the data every time.

My solution: 
1. Delete the implementation of IDataAccess from SqliteDataAccess.
2. It's too complicated to try and adapt that IDataAccess interface for both SqliteCrud and TextFileDataAccess so I recommend removing all the text file data access and switching to Sqlite. I know it's not a great idea to just delete stuff but it's early development so it's not much work.
3. After you do that, implement IDataAccess for SqliteCrud, change the method names and arguments so they match. Then go to App.xaml.cs. For the dataAccess variable create an instance for SqliteCrud, providing it the connectionString that it needs.

The idea of the interface was that both TextFileDataAccess and SqliteCrud implement it and we can switch between what data access is used. But they are too different.
I will let you do it so you can practice this stuff, instead of giving you a huge pull request. 
Good luck and ask any question you have.

**Comment by hartkemd** [comment]
Thanks. I saw some problems with it too, when I was working on it yesterday - I saw what you said about the text file data access and the SQLite data access not lining up.

I'll take a closer look after I get off work. It's nice to have someone reviewing my code, so I don't feel too alone - thanks.

**Comment by hartkemd** [comment]
How does this new commit look?

**Comment by MadalinCernat** [comment]
Good. Is it working as expected?

**Comment by hartkemd** [comment]
Yes, except the Move Up/Move Down and Sort A->Z features no longer work. I can think of a way to make the Sort A->Z to work again (such as an ORDER BY SQL statement), but the Move Up/Move Down features are trickier.. Do you have any ideas about how they could be fixed simply, or would it be complicated to make them work with a SQL DB?

**Comment by MadalinCernat** [comment]
You will have to add a new property for TextItemModel named Position.
Then, at the creation of a text item, you will assign it a Position equal to the count of the records in the database (this way it gets the highest one)
When you move down / move up, you will interchange the positions for the two items that are changing positions and update them in the database.
When you sort A->Z, you sort the list of items and assign positions properly, updating them in the database.
In the UI, make sure the list (textItems) is sorted by Position.
Note: Position should start from 0.

I'm not sure I've entirely thought this through but this is the idea. Other problems might appear, I'm not sure. But it looks like it'll be working this way.

**Comment by hartkemd** [comment]
Thanks. I started working on the moving and sorting, but let's close this issue (and, if we need to, open another one), because the title no longer reflects the subject of the conversation.
